// <auto-generated />
using System;
using AutoServis.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoServis.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251008174146_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutoServis.Core.Models.Dio", b =>
                {
                    b.Property<int>("DioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("KolicinaNaLageru")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("longtext");

                    b.HasKey("DioId");

                    b.ToTable("Djelovi");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Klijent", b =>
                {
                    b.Property<int>("KlijentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .HasColumnType("longtext");

                    b.Property<string>("Kontakt")
                        .HasColumnType("longtext");

                    b.Property<string>("KorisnickoIme")
                        .HasColumnType("longtext");

                    b.Property<string>("Lozinka")
                        .HasColumnType("longtext");

                    b.HasKey("KlijentID");

                    b.ToTable("Klijenti");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Racun", b =>
                {
                    b.Property<int>("RacunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BrojRacuna")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("DatumIzdavanja")
                        .HasColumnType("date");

                    b.Property<int>("KlijentID")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaID")
                        .HasColumnType("int");

                    b.Property<decimal?>("UkupnaCijena")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("RacunID");

                    b.HasIndex("KlijentID");

                    b.HasIndex("RezervacijaID");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Radnik", b =>
                {
                    b.Property<int>("RadnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kontakt")
                        .HasColumnType("longtext");

                    b.Property<string>("Prezime")
                        .HasColumnType("longtext");

                    b.HasKey("RadnikId");

                    b.ToTable("Radnici");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Rezervacija", b =>
                {
                    b.Property<int>("RezervacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DatumRezervacije")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DatumUsluge")
                        .HasColumnType("date");

                    b.Property<int>("KlijentID")
                        .HasColumnType("int");

                    b.Property<string>("OpisProblema")
                        .HasColumnType("longtext");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("RezervacijaID");

                    b.HasIndex("KlijentID");

                    b.HasIndex("StatusId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("longtext");

                    b.HasKey("StatusId");

                    b.ToTable("Statusi");
                });

            modelBuilder.Entity("AutoServis.Core.Models.TipUsluge", b =>
                {
                    b.Property<int>("TipUslugeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("Cijena")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Naziv")
                        .HasColumnType("longtext");

                    b.HasKey("TipUslugeID");

                    b.ToTable("TipoviUsluge");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Usluga", b =>
                {
                    b.Property<int>("UslugaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("BrojRadnihSati")
                        .HasColumnType("int");

                    b.Property<int>("RadnikId")
                        .HasColumnType("int");

                    b.Property<int>("RezervacijaID")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TipID")
                        .HasColumnType("int");

                    b.Property<int>("TipUslugeID")
                        .HasColumnType("int");

                    b.HasKey("UslugaId");

                    b.HasIndex("RadnikId");

                    b.HasIndex("RezervacijaID");

                    b.HasIndex("StatusId");

                    b.HasIndex("TipUslugeID");

                    b.ToTable("Usluge");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Vozilo", b =>
                {
                    b.Property<int>("VoziloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GodinaProizvodnje")
                        .HasColumnType("int");

                    b.Property<int>("KlijentID")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("longtext");

                    b.HasKey("VoziloID");

                    b.HasIndex("KlijentID");

                    b.ToTable("Vozila");
                });

            modelBuilder.Entity("DioUsluga", b =>
                {
                    b.Property<int>("DjeloviDioId")
                        .HasColumnType("int");

                    b.Property<int>("UslugeUslugaId")
                        .HasColumnType("int");

                    b.HasKey("DjeloviDioId", "UslugeUslugaId");

                    b.HasIndex("UslugeUslugaId");

                    b.ToTable("DIO_has_USLUGA", (string)null);
                });

            modelBuilder.Entity("StavkaRacuna", b =>
                {
                    b.Property<int>("StavkaRacunaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("CijenaPoJedinici")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Kolicina")
                        .HasColumnType("int");

                    b.Property<int>("RacunID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Ukupno")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UslugaId")
                        .HasColumnType("int");

                    b.HasKey("StavkaRacunaId");

                    b.HasIndex("RacunID");

                    b.HasIndex("UslugaId");

                    b.ToTable("StavkeRacuna");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Racun", b =>
                {
                    b.HasOne("AutoServis.Core.Models.Klijent", "Klijent")
                        .WithMany()
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServis.Core.Models.Rezervacija", "Rezervacija")
                        .WithMany("Racuni")
                        .HasForeignKey("RezervacijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("Rezervacija");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Rezervacija", b =>
                {
                    b.HasOne("AutoServis.Core.Models.Klijent", "Klijent")
                        .WithMany("Rezervacije")
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServis.Core.Models.Status", "Status")
                        .WithMany("Rezervacije")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klijent");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Usluga", b =>
                {
                    b.HasOne("AutoServis.Core.Models.Radnik", "Radnik")
                        .WithMany("Usluge")
                        .HasForeignKey("RadnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServis.Core.Models.Rezervacija", "Rezervacija")
                        .WithMany("Usluge")
                        .HasForeignKey("RezervacijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServis.Core.Models.Status", "Status")
                        .WithMany("Usluge")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServis.Core.Models.TipUsluge", "TipUsluge")
                        .WithMany("Usluge")
                        .HasForeignKey("TipUslugeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Radnik");

                    b.Navigation("Rezervacija");

                    b.Navigation("Status");

                    b.Navigation("TipUsluge");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Vozilo", b =>
                {
                    b.HasOne("AutoServis.Core.Models.Klijent", "Klijent")
                        .WithMany("Vozila")
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Klijent");
                });

            modelBuilder.Entity("DioUsluga", b =>
                {
                    b.HasOne("AutoServis.Core.Models.Dio", null)
                        .WithMany()
                        .HasForeignKey("DjeloviDioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServis.Core.Models.Usluga", null)
                        .WithMany()
                        .HasForeignKey("UslugeUslugaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StavkaRacuna", b =>
                {
                    b.HasOne("AutoServis.Core.Models.Racun", "Racun")
                        .WithMany("StavkeRacuna")
                        .HasForeignKey("RacunID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoServis.Core.Models.Usluga", "Usluga")
                        .WithMany("StavkeRacuna")
                        .HasForeignKey("UslugaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Racun");

                    b.Navigation("Usluga");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Klijent", b =>
                {
                    b.Navigation("Rezervacije");

                    b.Navigation("Vozila");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Racun", b =>
                {
                    b.Navigation("StavkeRacuna");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Radnik", b =>
                {
                    b.Navigation("Usluge");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Rezervacija", b =>
                {
                    b.Navigation("Racuni");

                    b.Navigation("Usluge");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Status", b =>
                {
                    b.Navigation("Rezervacije");

                    b.Navigation("Usluge");
                });

            modelBuilder.Entity("AutoServis.Core.Models.TipUsluge", b =>
                {
                    b.Navigation("Usluge");
                });

            modelBuilder.Entity("AutoServis.Core.Models.Usluga", b =>
                {
                    b.Navigation("StavkeRacuna");
                });
#pragma warning restore 612, 618
        }
    }
}
